/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author gabriel
 */
import cadastro.Cad_Cidade;
import cadastro.Clientes;
import ultilitarios.*;
import javax.swing.*;
public class TelaPrincipal extends javax.swing.JFrame {
    Data mostra_data = new Data();
   

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        
        
        mostra_data.le_data();
        label_data.setText(mostra_data.dia_semana+" , "+mostra_data.dia+" de "+mostra_data.mes+" de "+mostra_data.ano);
        
        timer1.start();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        timer1 = new org.netbeans.examples.lib.timerbean.Timer();
        panel_cidade = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        botao_cidade = new javax.swing.JButton();
        botao_bairros = new javax.swing.JButton();
        botao_sair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        label_data = new javax.swing.JLabel();
        label_hora = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        cadastro = new javax.swing.JMenu();
        menu_clientes = new javax.swing.JMenuItem();
        menu_funcionarios = new javax.swing.JMenuItem();
        menu_cidades = new javax.swing.JMenuItem();
        menu_cidade = new javax.swing.JMenuItem();
        menu_bairro = new javax.swing.JMenuItem();
        menu_cargo = new javax.swing.JMenuItem();
        menu_fornecedores = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menu_estoque = new javax.swing.JMenu();
        menu_implatacao = new javax.swing.JMenuItem();
        menu_entrada = new javax.swing.JMenuItem();
        menu_saida = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menu_sair2 = new javax.swing.JMenuItem();
        consultas = new javax.swing.JMenu();
        relatorios = new javax.swing.JMenu();
        ultilitarios = new javax.swing.JMenu();
        sair = new javax.swing.JMenu();

        timer1.addTimerListener(new org.netbeans.examples.lib.timerbean.TimerListener() {
            public void onTime(java.awt.event.ActionEvent evt) {
                timer1OnTime(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Controle de estoque");

        panel_cidade.setBackground(java.awt.Color.green);

        jButton1.setIcon(new javax.swing.ImageIcon("/home/gabriel/NetBeansProjects/Estoque/imagens/users.png")); // NOI18N
        jButton1.setText("Clientes");

        botao_cidade.setIcon(new javax.swing.ImageIcon("/home/gabriel/NetBeansProjects/Estoque/imagens/cidade.png")); // NOI18N
        botao_cidade.setText("Cidades");
        botao_cidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_cidadeActionPerformed(evt);
            }
        });

        botao_bairros.setText("Bairros");

        botao_sair.setIcon(new javax.swing.ImageIcon("/home/gabriel/NetBeansProjects/Estoque/imagens/exit.png")); // NOI18N
        botao_sair.setText("Sair");
        botao_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_sairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_cidadeLayout = new javax.swing.GroupLayout(panel_cidade);
        panel_cidade.setLayout(panel_cidadeLayout);
        panel_cidadeLayout.setHorizontalGroup(
            panel_cidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cidadeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(82, 82, 82)
                .addComponent(botao_cidade)
                .addGap(75, 75, 75)
                .addComponent(botao_bairros)
                .addGap(83, 83, 83)
                .addComponent(botao_sair)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_cidadeLayout.setVerticalGroup(
            panel_cidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cidadeLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panel_cidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(botao_cidade)
                    .addComponent(botao_bairros)
                    .addComponent(botao_sair))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jLabel1.setText("Desenvolvidor por Gabriel Lima");

        label_data.setText("Data:");

        label_hora.setText("Hora");

        cadastro.setText("Cadastro");

        menu_clientes.setIcon(new javax.swing.ImageIcon("/home/gabriel/NetBeansProjects/Estoque/imagens/users.png")); // NOI18N
        menu_clientes.setText("Clientes");
        menu_clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_clientesActionPerformed(evt);
            }
        });
        cadastro.add(menu_clientes);

        menu_funcionarios.setText("Funcionarios");
        cadastro.add(menu_funcionarios);

        menu_cidades.setText("Cidades");
        cadastro.add(menu_cidades);

        menu_cidade.setText("Cidade");
        cadastro.add(menu_cidade);

        menu_bairro.setText("Bairro");
        cadastro.add(menu_bairro);

        menu_cargo.setText("Cargo");
        cadastro.add(menu_cargo);

        menu_fornecedores.setText("Fornecedores");
        cadastro.add(menu_fornecedores);
        cadastro.add(jSeparator1);

        menu_estoque.setText("Estoque");

        menu_implatacao.setText("Implatação");
        menu_estoque.add(menu_implatacao);

        menu_entrada.setText("Entrada");
        menu_estoque.add(menu_entrada);

        menu_saida.setText("Saída");
        menu_estoque.add(menu_saida);

        cadastro.add(menu_estoque);
        cadastro.add(jSeparator2);

        menu_sair2.setText("Sair");
        menu_sair2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_sair2ActionPerformed(evt);
            }
        });
        cadastro.add(menu_sair2);

        jMenuBar1.add(cadastro);

        consultas.setText("Consultas");
        jMenuBar1.add(consultas);

        relatorios.setText("Relatórios");
        jMenuBar1.add(relatorios);

        ultilitarios.setText("Ultilitarios");
        jMenuBar1.add(ultilitarios);

        sair.setText("Sair");
        sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sairMouseClicked(evt);
            }
        });
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });
        jMenuBar1.add(sair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_cidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(label_data)
                        .addGap(209, 209, 209)
                        .addComponent(label_hora)))
                .addContainerGap(386, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_data)
                    .addComponent(label_hora)))
        );

        setBounds(0, 0, 800, 600);
    }// </editor-fold>//GEN-END:initComponents

    private void timer1OnTime(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timer1OnTime
        mostra_data.le_hora();
        label_hora.setText(mostra_data.hora);    }//GEN-LAST:event_timer1OnTime

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
        

    }//GEN-LAST:event_sairActionPerformed

    private void menu_sair2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_sair2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menu_sair2ActionPerformed

    private void sairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sairMouseClicked
        System.exit(0);
    }//GEN-LAST:event_sairMouseClicked

    private void menu_clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_clientesActionPerformed
        
    }//GEN-LAST:event_menu_clientesActionPerformed

    private void botao_cidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_cidadeActionPerformed
        
        new Cad_Cidade().show();
        
    }//GEN-LAST:event_botao_cidadeActionPerformed

    private void botao_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_sairActionPerformed
       System.exit(0);
    }//GEN-LAST:event_botao_sairActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao_bairros;
    private javax.swing.JButton botao_cidade;
    private javax.swing.JButton botao_sair;
    private javax.swing.JMenu cadastro;
    private javax.swing.JMenu consultas;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JLabel label_data;
    private javax.swing.JLabel label_hora;
    private javax.swing.JMenuItem menu_bairro;
    private javax.swing.JMenuItem menu_cargo;
    private javax.swing.JMenuItem menu_cidade;
    private javax.swing.JMenuItem menu_cidades;
    private javax.swing.JMenuItem menu_clientes;
    private javax.swing.JMenuItem menu_entrada;
    private javax.swing.JMenu menu_estoque;
    private javax.swing.JMenuItem menu_fornecedores;
    private javax.swing.JMenuItem menu_funcionarios;
    private javax.swing.JMenuItem menu_implatacao;
    private javax.swing.JMenuItem menu_saida;
    private javax.swing.JMenuItem menu_sair2;
    private javax.swing.JPanel panel_cidade;
    private javax.swing.JMenu relatorios;
    private javax.swing.JMenu sair;
    private org.netbeans.examples.lib.timerbean.Timer timer1;
    private javax.swing.JMenu ultilitarios;
    // End of variables declaration//GEN-END:variables
    
    
}

